bind_port = 3128
bind_ip = "0.0.0.0"
zyte_smartproxy_port = 8011
zyte_smartproxy_host = "proxy.zyte.com"
api_key = "USER_API_KEY"
adblock_lists = [
  "https://fanboy.co.nz/r/fanboy-ultimate.txt",
  "https://fanboy.co.nz/fanboy-antifonts.txt",
  "https://fanboy.co.nz/fanboy-antifacebook.txt",
  "https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt"
]

[zyte_smartproxy_headers]
cookies = "disable"
profile = "desktop"
