---

version: "2"
services:
  splash:
    image: zytedata/splash
    ports:
      - 8050:8050
      - 5023:5023

  headless-proxy:
    image: zyte-smartproxy-headless-proxy
    ports:
      - 3128:3128
    environment:
      ZYTE_SMARTPROXY_HEADLESS_PROXY_APIKEY: USER_API_KEY
    networks:
      default:
        aliases:
          - proxy
