#!/bin/sh
set -eu

PROJECT_DIR="$(git rev-parse --show-toplevel)"
CA_FILE="${PROJECT_DIR}/ca.crt"
PRIV_FILE="${PROJECT_DIR}/private-key.pem"
OUTPUT_FILE="${PROJECT_DIR}/proxy/certs.go"

cat > "$OUTPUT_FILE" <<EOF
package proxy
// autogenerated by $(basename "$0") on $(date --rfc-2822 --utc)

var certCA = []byte(\`$(cat "$CA_FILE")\`)

var certKey = []byte(\`$(cat "$PRIV_FILE")\`)
EOF
